name: Deploy a VM to GCP

on:
  push:
    branches:
      - dev
      - qa
      - main

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read  # Default permission for accessing the repo

jobs:
  deploy:
    name: Create GCP Storage Bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/985414759644/locations/global/workloadIdentityPools/github-id-pool/providers/github-actions'
          service_account: 'github-actions-sa@master-358906.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Create GCS bucket
        run: |
          gsutil mb -l US-CENTRAL1 gs://my-unique-bucket-name-${{ github.run_number }}