name: Deploy to GCP

on:
  push:
    branches:
      - dev
      - qa
      - main

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read  # Default permission for accessing the repo

jobs:
  deploy:
    name: Create GCP Storage Bucket
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/master-358906/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-fpittelo@master-358906.iam.gserviceaccount.com' 
          project_id: 'master-358906'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Create GCS bucket
        run: |
          gsutil mb -l US gs://fpittelo-google-vm-bckend