name: Deploy to GCP

on:
  push:
    branches:
      - dev
      - qa
      - main

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Default permission for accessing the repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/master-358906/locations/global/workloadIdentityPools/github-actions/providers/github-actions-pool'
          service_account: 'google-github-actions@master-358906.iam.gserviceaccount.com'

      - name: Set environment based on branch
        id: setenv
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/qa" ]]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=main" >> $GITHUB_ENV
          fi

      - name: Deploy VM
        run: |
          gcloud compute instances create iaac-gcp-vm-01 \
            --project=master-358906 \
            --zone=${{ env.ZONE }} \
            --machine-type=${{ env.MACHINE_TYPE }} \
            --subnet=default \
            --network-tier=PREMIUM \
            --maintenance-policy=MIGRATE \
            --service-account=google-github-actions@master-358906.iam.gserviceaccount.com \
            --scopes=https://www.googleapis.com/auth/cloud-platform \
            --tags=http-server,https-server \
            --image-family=ubuntu-2204-lts \
            --image-project=ubuntu-os-cloud \
            --boot-disk-size=10GB \
            --boot-disk-type=pd-standard \
            --boot-disk-device-name=iaac-gcp-vm-01

env:
  ZONE: europe-west6-b
  MACHINE_TYPE: e2-micro