name: Deploy to GCP

on:
  push:
    branches:
      - dev
      - qa
      - main

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read  # Default permission for accessing the repo

jobs:
  deploy:
    name: Deploy GCP VM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/master-358906/locations/global/workloadIdentityPools/deploy-pool/providers/github-provider'
          service_account: 'github-srv-acct'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Create GCS bucket
        run: |
          gsutil mb -l US gs://my-new-bucket-unique-name