name: Destroy GCP Resources

on:
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Default permission for accessing the repo

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/master-358906/locations/global/workloadIdentityPools/[POOL_ID]/providers/[PROVIDER_ID]'
          service_account: 'google-github-actions@master-358906.iam.gserviceaccount.com'

      - name: Destroy VM
        run: |
          gcloud compute instances delete iaac-gcp-vm-01 \
            --project=master-358906 \
            --zone=${{ env.ZONE }} \
            --quiet

env:
  ZONE: europe-west6-b